sudo service snowplow_stream_collector restart
sudo service snowplow_stream_enrich restart
sudo service snowplow_elasticsearch_loader_good restart
sudo service snowplow_elasticsearch_loader_bad restart
